import Head from "next/head";
import Image from "next/image";
import localFont from "next/font/local";
import styles from "@/styles/Home.module.css";
import { motion } from "framer-motion";
import { ThemeProvider } from "@emotion/react";
import theme from "@/lib/createTheme";
import { Button } from "@mui/material";
import { useRouter } from "next/router";
const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export default function Home() {
  const router = useRouter();

  const handleClick = () => {
    router.push("/sign-up");
  };

  return (
    <>
      <ThemeProvider theme={theme}>
        <Head>
          <title>SoundFusion</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <div
          className={`${styles.page} ${geistSans.variable} ${geistMono.variable}`}
        >
          <main className={styles.main}>
            <motion.h1
              initial={{ opacity: 0, y: -50 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ duration: 1 }}
            >
              SoundFusion
            </motion.h1>
            <motion.h4
              initial={{ opacity: 0 }}
              animate={{ opacity: 1 }}
              transition={{ duration: 1, delay: 0.5 }}
            >
              Место, в котором объединяться все музыканты
            </motion.h4>{" "}
            <Button onClick={handleClick}>Зарегистрироваться</Button>
          </main>
        </div>
      </ThemeProvider>
    </>
  );
}
