import Head from "next/head";
import Image from "next/image";
import styles from "@/styles/Home.module.css";
import { motion } from "framer-motion";
import { ThemeProvider } from "@emotion/react";
import theme from "@/lib/createTheme";
import { Button } from "@mui/material";
import { useRouter } from "next/router";

import { geistSans, geistMono } from "@/lib/fonts";

export default function Home() {
  const router = useRouter();

  const handleLogin = () => {
    router.push("/sign-in");
  };

  return (
    <>
      <ThemeProvider theme={theme}>
        <Head>
          <title>SoundFusion</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <div
          className={`${styles.page} ${geistSans.variable} ${geistMono.variable}`}
        >
          <main className={styles.main}>
            <motion.h1
              initial={{ opacity: 0, y: -50 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ duration: 1 }}
            >
              SoundFusion
            </motion.h1>
            <motion.h4
              initial={{ opacity: 0 }}
              animate={{ opacity: 1 }}
              transition={{ duration: 1, delay: 0.5 }}
            >
              Место, в котором объединяться все музыканты
            </motion.h4>{" "}
            <div className={styles.buttonGroup}>
              <Button onClick={handleLogin} variant="outlined" color="primary">
                Войти
              </Button>
            </div>
          </main>
        </div>
      </ThemeProvider>
    </>
  );
}
